// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanPizza.Models;

#nullable disable

namespace WebBanPizza.Migrations
{
    [DbContext(typeof(PizzaDbContext))]
    [Migration("20250808161449_AddDaThanhToanToDonHang")]
    partial class AddDaThanhToanToDonHang
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebBanPizza.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChiTietId"));

                    b.Property<int?>("DonHangId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("ChiTietId")
                        .HasName("PK__ChiTietD__B117E9CAEF7626C3");

                    b.HasIndex("DonHangId");

                    b.HasIndex("PizzaId");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CouponId"));

                    b.Property<int?>("GiamGiaPhanTram")
                        .HasColumnType("int");

                    b.Property<string>("Ma")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("datetime");

                    b.HasKey("CouponId")
                        .HasName("PK__Coupon__384AF1BA74FCFB76");

                    b.ToTable("Coupon", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.DanhGium", b =>
                {
                    b.Property<int>("DanhGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhGiaId"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int?>("SoSao")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DanhGiaId")
                        .HasName("PK__DanhGia__52C0CA0522F98AD3");

                    b.HasIndex("PizzaId");

                    b.HasIndex("UserId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("WebBanPizza.Models.DanhMuc", b =>
                {
                    b.Property<int>("DanhMucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DanhMucId"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DanhMucId")
                        .HasName("PK__DanhMuc__1C53A59BC6C42238");

                    b.ToTable("DanhMuc", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.DiaChi", b =>
                {
                    b.Property<int>("DiaChiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiaChiId"));

                    b.Property<string>("DiaChiChiTiet")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DiaChiId")
                        .HasName("PK__DiaChi__94E668C6D2B90B3C");

                    b.HasIndex("UserId");

                    b.ToTable("DiaChi", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.DonHang", b =>
                {
                    b.Property<int>("DonHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonHangId"));

                    b.Property<int?>("CouponId")
                        .HasColumnType("int");

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("bit");

                    b.Property<int?>("DiaChiId")
                        .HasColumnType("int");

                    b.Property<string>("MaKhuyenMai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayDat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("PhuongThucId")
                        .HasColumnType("int");

                    b.Property<int?>("ShipperId")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Chờ xử lý");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("DonHangId")
                        .HasName("PK__DonHang__D159F4BE71CB6806");

                    b.HasIndex("CouponId");

                    b.HasIndex("DiaChiId");

                    b.HasIndex("PhuongThucId");

                    b.HasIndex("ShipperId");

                    b.HasIndex("UserId");

                    b.ToTable("DonHang", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.GioHang", b =>
                {
                    b.Property<int>("GioHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GioHangId"));

                    b.Property<int?>("PizzaId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("GioHangId")
                        .HasName("PK__GioHang__4242286D94FA22C6");

                    b.HasIndex("PizzaId");

                    b.HasIndex("UserId");

                    b.ToTable("GioHang", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DonHangId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ThoiGian")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("TrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__LichSuTr__3214EC07A5BA47C8");

                    b.HasIndex("DonHangId");

                    b.ToTable("LichSuTrangThaiDonHang", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.NguoiDung", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("VaiTro")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserId")
                        .HasName("PK__NguoiDun__1788CC4CD3F8AB1B");

                    b.HasIndex(new[] { "Email" }, "UQ__NguoiDun__A9D105349FAAB1B1")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("NguoiDung", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("PhuongThucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhuongThucId"));

                    b.Property<string>("TenPhuongThuc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PhuongThucId")
                        .HasName("PK__PhuongTh__1E306C6372D4D71D");

                    b.ToTable("PhuongThucThanhToan", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PizzaId"));

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("HinhAnh")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("KichThuoc")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PizzaId")
                        .HasName("PK__Pizza__0B6012DDF4BD9403");

                    b.HasIndex("DanhMucId");

                    b.ToTable("Pizza", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebBanPizza.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId")
                        .HasConstraintName("FK__ChiTietDo__DonHa__6477ECF3");

                    b.HasOne("WebBanPizza.Models.Pizza", "Pizza")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK__ChiTietDo__Pizza__656C112C");

                    b.Navigation("DonHang");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("WebBanPizza.Models.DanhGium", b =>
                {
                    b.HasOne("WebBanPizza.Models.Pizza", "Pizza")
                        .WithMany("DanhGia")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK__DanhGia__PizzaId__66603565");

                    b.HasOne("WebBanPizza.Models.NguoiDung", "User")
                        .WithMany("DanhGia")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__DanhGia__UserId__6754599E");

                    b.Navigation("Pizza");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanPizza.Models.DiaChi", b =>
                {
                    b.HasOne("WebBanPizza.Models.NguoiDung", "User")
                        .WithMany("DiaChis")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__DiaChi__UserId__68487DD7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanPizza.Models.DonHang", b =>
                {
                    b.HasOne("WebBanPizza.Models.Coupon", "Coupon")
                        .WithMany("DonHangs")
                        .HasForeignKey("CouponId")
                        .HasConstraintName("FK__DonHang__CouponI__6C190EBB");

                    b.HasOne("WebBanPizza.Models.DiaChi", "DiaChi")
                        .WithMany("DonHangs")
                        .HasForeignKey("DiaChiId")
                        .HasConstraintName("FK__DonHang__DiaChiI__6A30C649");

                    b.HasOne("WebBanPizza.Models.PhuongThucThanhToan", "PhuongThuc")
                        .WithMany("DonHangs")
                        .HasForeignKey("PhuongThucId")
                        .HasConstraintName("FK__DonHang__PhuongT__6B24EA82");

                    b.HasOne("WebBanPizza.Models.NguoiDung", "Shipper")
                        .WithMany("DonHangShippers")
                        .HasForeignKey("ShipperId")
                        .HasConstraintName("FK_DonHang_Shipper");

                    b.HasOne("WebBanPizza.Models.NguoiDung", "User")
                        .WithMany("DonHangUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__DonHang__UserId__693CA210");

                    b.Navigation("Coupon");

                    b.Navigation("DiaChi");

                    b.Navigation("PhuongThuc");

                    b.Navigation("Shipper");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanPizza.Models.GioHang", b =>
                {
                    b.HasOne("WebBanPizza.Models.Pizza", "Pizza")
                        .WithMany("GioHangs")
                        .HasForeignKey("PizzaId")
                        .HasConstraintName("FK__GioHang__PizzaId__6EF57B66");

                    b.HasOne("WebBanPizza.Models.NguoiDung", "User")
                        .WithMany("GioHangs")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__GioHang__UserId__6E01572D");

                    b.Navigation("Pizza");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanPizza.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.HasOne("WebBanPizza.Models.DonHang", "DonHang")
                        .WithMany("LichSuTrangThaiDonHangs")
                        .HasForeignKey("DonHangId")
                        .HasConstraintName("FK__LichSuTra__DonHa__6FE99F9F");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("WebBanPizza.Models.Pizza", b =>
                {
                    b.HasOne("WebBanPizza.Models.DanhMuc", "DanhMuc")
                        .WithMany("Pizzas")
                        .HasForeignKey("DanhMucId")
                        .HasConstraintName("FK__Pizza__DanhMucId__70DDC3D8");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("WebBanPizza.Models.Coupon", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.DanhMuc", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("WebBanPizza.Models.DiaChi", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LichSuTrangThaiDonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DiaChis");

                    b.Navigation("DonHangShippers");

                    b.Navigation("DonHangUsers");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.Pizza", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGia");

                    b.Navigation("GioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
