// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WebBanPizza.Models;

#nullable disable

namespace WebBanPizza.Migrations
{
    [DbContext(typeof(PizzaDbContext))]
    [Migration("20250829194839_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WebBanPizza.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("ChiTietId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChiTietId"));

                    b.Property<int?>("DonHangId")
                        .HasColumnType("integer");

                    b.Property<string>("GhiChu")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("PizzaId")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.HasKey("ChiTietId");

                    b.HasIndex("DonHangId");

                    b.HasIndex("PizzaId");

                    b.ToTable("ChiTietDonHang", (string)null);
                });

            modelBuilder.Entity("WebBanPizza.Models.Coupon", b =>
                {
                    b.Property<int>("CouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CouponId"));

                    b.Property<int?>("GiamGiaPhanTram")
                        .HasColumnType("integer");

                    b.Property<string>("Ma")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayHetHan")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CouponId");

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("WebBanPizza.Models.DanhGia", b =>
                {
                    b.Property<int>("DanhGiaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DanhGiaId"));

                    b.Property<string>("BinhLuan")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayDanhGia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("PizzaId")
                        .HasColumnType("integer");

                    b.Property<int?>("SoSao")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("DanhGiaId");

                    b.HasIndex("PizzaId");

                    b.HasIndex("UserId");

                    b.ToTable("DanhGia");
                });

            modelBuilder.Entity("WebBanPizza.Models.DanhMuc", b =>
                {
                    b.Property<int>("DanhMucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DanhMucId"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DanhMucId");

                    b.ToTable("DanhMucs");
                });

            modelBuilder.Entity("WebBanPizza.Models.DiaChi", b =>
                {
                    b.Property<int>("DiaChiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DiaChiId"));

                    b.Property<string>("DiaChiChiTiet")
                        .HasColumnType("text");

                    b.Property<string>("Duong")
                        .HasColumnType("text");

                    b.Property<string>("GhiChu")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .HasColumnType("text");

                    b.Property<bool>("MacDinh")
                        .HasColumnType("boolean");

                    b.Property<string>("QuanHuyen")
                        .HasColumnType("text");

                    b.Property<string>("Sdt")
                        .HasColumnType("text");

                    b.Property<string>("SoDienThoai")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("DiaChiId");

                    b.HasIndex("UserId");

                    b.ToTable("DiaChis");
                });

            modelBuilder.Entity("WebBanPizza.Models.DonHang", b =>
                {
                    b.Property<int>("DonHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DonHangId"));

                    b.Property<int?>("CouponId")
                        .HasColumnType("integer");

                    b.Property<bool>("DaThanhToan")
                        .HasColumnType("boolean");

                    b.Property<string>("DiaChiGiao")
                        .HasColumnType("text");

                    b.Property<int?>("DiaChiId")
                        .HasColumnType("integer");

                    b.Property<string>("MaKhuyenMai")
                        .HasColumnType("text");

                    b.Property<DateTime?>("NgayDat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("PhiShip")
                        .HasColumnType("numeric");

                    b.Property<int?>("PhuongThucId")
                        .HasColumnType("integer");

                    b.Property<string>("SdtnguoiNhan")
                        .HasColumnType("text");

                    b.Property<int?>("ShipperId")
                        .HasColumnType("integer");

                    b.Property<decimal>("SoTienGiam")
                        .HasColumnType("numeric");

                    b.Property<string>("TenNguoiNhan")
                        .HasColumnType("text");

                    b.Property<decimal?>("TongTien")
                        .HasColumnType("numeric");

                    b.Property<string>("TrangThai")
                        .HasColumnType("text");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("DonHangId");

                    b.HasIndex("CouponId");

                    b.HasIndex("DiaChiId");

                    b.HasIndex("PhuongThucId");

                    b.HasIndex("ShipperId");

                    b.HasIndex("UserId");

                    b.ToTable("DonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.GioHang", b =>
                {
                    b.Property<int>("GioHangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GioHangId"));

                    b.Property<int?>("PizzaId")
                        .HasColumnType("integer");

                    b.Property<int>("SoLuong")
                        .HasColumnType("integer");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("GioHangId");

                    b.HasIndex("PizzaId");

                    b.HasIndex("UserId");

                    b.ToTable("GioHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DonHangId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ThoiGian")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrangThai")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.ToTable("LichSuTrangThaiDonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.NguoiDung", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("HoTen")
                        .HasColumnType("text");

                    b.Property<string>("MatKhau")
                        .HasColumnType("text");

                    b.Property<string>("VaiTro")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("NguoiDungs");
                });

            modelBuilder.Entity("WebBanPizza.Models.PhuongThucThanhToan", b =>
                {
                    b.Property<int>("PhuongThucId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PhuongThucId"));

                    b.Property<string>("TenPhuongThuc")
                        .HasColumnType("text");

                    b.HasKey("PhuongThucId");

                    b.ToTable("PhuongThucThanhToans");
                });

            modelBuilder.Entity("WebBanPizza.Models.Pizza", b =>
                {
                    b.Property<int>("PizzaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PizzaId"));

                    b.Property<int?>("DanhMucId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Gia")
                        .HasColumnType("numeric");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("text");

                    b.Property<string>("KichThuoc")
                        .HasColumnType("text");

                    b.Property<string>("MoTa")
                        .HasColumnType("text");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PizzaId");

                    b.HasIndex("DanhMucId");

                    b.ToTable("Pizzas");
                });

            modelBuilder.Entity("WebBanPizza.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("WebBanPizza.Models.DonHang", "DonHang")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("DonHangId");

                    b.HasOne("WebBanPizza.Models.Pizza", "Pizza")
                        .WithMany("ChiTietDonHangs")
                        .HasForeignKey("PizzaId");

                    b.Navigation("DonHang");

                    b.Navigation("Pizza");
                });

            modelBuilder.Entity("WebBanPizza.Models.DanhGia", b =>
                {
                    b.HasOne("WebBanPizza.Models.Pizza", "Pizza")
                        .WithMany("DanhGia")
                        .HasForeignKey("PizzaId");

                    b.HasOne("WebBanPizza.Models.NguoiDung", "User")
                        .WithMany("DanhGia")
                        .HasForeignKey("UserId");

                    b.Navigation("Pizza");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanPizza.Models.DiaChi", b =>
                {
                    b.HasOne("WebBanPizza.Models.NguoiDung", "User")
                        .WithMany("DiaChis")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanPizza.Models.DonHang", b =>
                {
                    b.HasOne("WebBanPizza.Models.Coupon", "Coupon")
                        .WithMany("DonHangs")
                        .HasForeignKey("CouponId");

                    b.HasOne("WebBanPizza.Models.DiaChi", "DiaChi")
                        .WithMany("DonHangs")
                        .HasForeignKey("DiaChiId");

                    b.HasOne("WebBanPizza.Models.PhuongThucThanhToan", "PhuongThuc")
                        .WithMany("DonHangs")
                        .HasForeignKey("PhuongThucId");

                    b.HasOne("WebBanPizza.Models.NguoiDung", "Shipper")
                        .WithMany("DonHangShippers")
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebBanPizza.Models.NguoiDung", "User")
                        .WithMany("DonHangUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coupon");

                    b.Navigation("DiaChi");

                    b.Navigation("PhuongThuc");

                    b.Navigation("Shipper");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanPizza.Models.GioHang", b =>
                {
                    b.HasOne("WebBanPizza.Models.Pizza", "Pizza")
                        .WithMany("GioHangs")
                        .HasForeignKey("PizzaId");

                    b.HasOne("WebBanPizza.Models.NguoiDung", "User")
                        .WithMany("GioHangs")
                        .HasForeignKey("UserId");

                    b.Navigation("Pizza");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebBanPizza.Models.LichSuTrangThaiDonHang", b =>
                {
                    b.HasOne("WebBanPizza.Models.DonHang", "DonHang")
                        .WithMany("LichSuTrangThaiDonHangs")
                        .HasForeignKey("DonHangId");

                    b.Navigation("DonHang");
                });

            modelBuilder.Entity("WebBanPizza.Models.Pizza", b =>
                {
                    b.HasOne("WebBanPizza.Models.DanhMuc", "DanhMuc")
                        .WithMany("Pizzas")
                        .HasForeignKey("DanhMucId");

                    b.Navigation("DanhMuc");
                });

            modelBuilder.Entity("WebBanPizza.Models.Coupon", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.DanhMuc", b =>
                {
                    b.Navigation("Pizzas");
                });

            modelBuilder.Entity("WebBanPizza.Models.DiaChi", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.DonHang", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("LichSuTrangThaiDonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGia");

                    b.Navigation("DiaChis");

                    b.Navigation("DonHangShippers");

                    b.Navigation("DonHangUsers");

                    b.Navigation("GioHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.PhuongThucThanhToan", b =>
                {
                    b.Navigation("DonHangs");
                });

            modelBuilder.Entity("WebBanPizza.Models.Pizza", b =>
                {
                    b.Navigation("ChiTietDonHangs");

                    b.Navigation("DanhGia");

                    b.Navigation("GioHangs");
                });
#pragma warning restore 612, 618
        }
    }
}
